### ISSUE TITLE
I/flutter ( 4414): ERROR: type 'String' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by adamsoftweb** [X-SLAYER/coronavirus-tracker#1]
Hi and thank you for your effort,

I have an issue with "Coronavirus Tracker".
This error **(I/flutter ( 4414): ERROR: type 'String' is not a subtype of type 'int')** is generated  when programm try to execute this function : 

```
 ///fill The list of places and reports
  getLists(dynamic decodedReports, dynamic decodedPlaces) {
    for (var item in decodedReports) {
      reports.add(Report.fromJson(item));
    }

    for (var item in decodedPlaces) {
      places.add(Place.fromJson(item));
    }
  }
```

I try many solutions to resolve it, but no way .. i'm beginner in flutter.
Thanks

**Comment by ghost** [comment]
closed#2

Le mer. 26 févr. 2020 à 16:26, adamsoftweb <notifications@github.com> a
écrit :
